#!/bin/sh

##
## configuration template file for CUBEmixer 
## 
## (this file follows the convention for bash-scripts)
##
## do NOT edit this file LocalVars.template.sh directly!
##
## instead COPY this file to LocalVars.sh and edit according
## to your needs (you can alo delete lines you don't care to set)
## when doing so, remove this paragraph
##
## do NOT REMOVE the file LocalVars.template.sh
## 
##  sending PD some specials initializer with the XX_MESSAGE vars see below.

##
## general settings regarding PD
##
#PD_INSTALL=src/pd/bin
#PD_OPTIONS=
PD_PATH="-path .:lib:lib/abs/:lib/libs/:lib/plugins/:lib/extensions/:lib/GUI/:lib/DSP/:lib/GUI/abs:lib/DSP/abs:lib/libs/iemabs:lib/libs/zexyabs"
PD_LIB="-lib zexy:iemlib1:iemlib2:iemmatrix:iem_ambi:iem_bin_ambi:iemgui:iem_spec2"

##
## settings regarding only the GUI-part of the CUBEmixer
##
GUI_PATCH="lib/GUI/GUI16+OUT.pd"
GUI_AUDIO="-nosound"
GUI_MIDI="-nomidi"
GUI_OPTIONS="-nrt"
# GUI_PATH=
# GUI_LIB=
#GUI_MESSAGE=""

##
## settings regarding only the DSP-part of the CUBEmixer
##
DSP_PATCH="lib/DSP/DSP+NET+MIDI+CUE.pd"
DSP_AUDIO="-alsa -channels 26 -r 44100 -audiobuf 23"
DSP_MIDI="-alsamidi -mididev 1,1"
DSP_OPTIONS="-rt"
#DSP_PATH=
#DSP_LIB=
#DSP_MESSAGE=""
