# Makefile for pure data class bitflip~ in lib kat.

lib.name := kat
class.sources := bitflip~.c
datafiles := bitflip~-help.pd

cflags := -I ../libhack

# Overridable path to find Makefile.pdlibbuilder.
ifndef PDLIBBUILDER_DIR
 PDLIBBUILDER_DIR := ..
endif

# Helper makefile.
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
