REM
REM configuration file for CUBEmixer on Windows(tm)
REM 
REM (this file follows the convention for .BAT files

REM
REM do NOT edit this file LocalVars.template.bat directly!
REM
REM instead COPY this file to LocalVars.bat and edit according
REM to your needs (you can alo delete lines you don't care to set)
REM when doing so, remove this paragraph
REM
REM do NOT REMOVE the file LocalVars.template.bat
REM 

REM
REM general settings regarding PD
REM
set PD_INSTALL=..\src\pd\bin
set PD_OPTIONS=-font 10
set PD_PATH=-path ..;../lib;../lib/abs/;../lib/libs/;../lib/plugins/;../lib/extensions/;../lib/GUI/;../lib/DSP/;../lib/GUI/abs;../lib/DSP/abs;../lib/libs/iemabs;../lib/libs/zexyabs
set PD_LIB=-lib zexy;iemlib1;iemlib2;iemmatrix;iem_ambi;iemgui

REM
REM settings regarding only the GUI-part of the CUBEmixer
REM
set GUI_PATCH=../lib/GUI/GUI16+OUT.pd
set GUI_AUDIO=-noaudio
set GUI_MIDI=-nomidi
REM set GUI_OPTIONS=
REM set GUI_PATH=
REM set GUI_LIB=


REM
REM settings regarding only the GUI-part of the CUBEmixer
REM
set DSP_PATCH=..\lib\DSP\DSP+NET+MIDI+CUE_WIN.pd
set DSP_AUDIO=-r 44100 -audiobuf 80 -sleepgrain 10 -channels 26
set DSP_MIDI=
REM set DSP_OPTIONS=
REM set DSP_PATH=
REM set DSP_LIB=
